name: Deploy to EC2 server
on:
  push:
    branches: [ "main" ]

jobs:
  Install-Packages:
    runs-on: self-hosted

    steps:
      - run: sudo apt install apache2 -y

  Build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present

  Staging:
    runs-on: self-hosted
    needs: ["Build"]
    environment:
      name: Staging
      url: https://staging-animequoter.thecenturist.com
    steps:
      - run: sudo cp -r /home/ubuntu/actions-runner/_work/anime-quoter/anime-quoter/dist/* ${{ secrets.PUBLIC_HTML_DIR }}
      - run: sudo systemctl restart apache2

  Deploy:
    runs-on: self-hosted
    needs: ["Staging"]
    environment:
      name: Production
      url: https://anime-quoter.thecenturist.com
    steps:
      - run: sudo cp -r /home/ubuntu/actions-runner/_work/anime-quoter/anime-quoter/dist/* ${{ secrets.PUBLIC_HTML_DIR }}
      - run: sudo systemctl restart apache2